name: CI
run-name: CI
on: 
  - workflow_dispatch
jobs:
  Build-Windows-x64:
    name: Build NATMap (Windows, x64)
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          location: D:\msys2
          update: true
      - name: Build NATMap_Win32
        shell: msys2 {0}
        run: |
          bash build.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: natmap_win32
          path: ${{ github.workspace }}/dist/natmap
